### ISSUE TITLE
IRDO.yml appears to have the wrong field ordering

### ISSUE THREAD

**Issue by BromBromBromley** [kingdom-of-ds-hacking/swan#2]
The ESDB supplied for B2 (IREO) appears to have the correct ordering, but the ESDB supplied here for W2 (IRDO). From what I can tell, the order should be something like this:
```yaml
Symbols:
  - Name: function_name
    Segment: 0x0
    Address: 0x2004000
```
However, the actual ordering appears like this:
```yaml
Symbols:
  - Address: 0x2004000
    Name: function_name
    Segment: 0x0
```
and it causes CTRMap to be unable to correctly link functions as a result.
